### ISSUE TITLE
Issue generating thumbnails

### ISSUE THREAD

**Issue by Ryonez** [mserajnik/hydrus-server-docker#2]
Traceback from client:
```
BadRequestException
Could not generate thumbnail from that file:
Traceback (most recent call last):
  File "/usr/src/app/include/HydrusServerResources.py", line 258, in ParseFileArguments
    thumbnail_bytes = HydrusFileHandling.GenerateThumbnailBytes( path, target_resolution, mime, duration, num_frames )
  File "/usr/src/app/include/HydrusFileHandling.py", line 101, in GenerateThumbnailBytes
    numpy_image = HydrusImageHandling.ResizeNumPyImage( numpy_image, target_resolution ) # just in case ffmpeg doesn't deliver right
  File "/usr/src/app/include/HydrusImageHandling.py", line 629, in ResizeNumPyImage
    interpolation = cv2.INTER_LANCZOS4
NameError: name 'cv2' is not defined

Traceback (most recent call last):
  File "include\HydrusThreading.py", line 342, in run
    callable( *args, **kwargs )
  File "include\ClientGUI.py", line 145, in THREADUploadPending
    service.Request( HC.POST, 'file', { 'file' : file_bytes } )
  File "include\ClientServices.py", line 902, in Request
    network_job.WaitUntilDone()
  File "include\ClientNetworkingJobs.py", line 1137, in WaitUntilDone
    raise self._error_exception
include.HydrusExceptions.BadRequestException: Could not generate thumbnail from that file:
Traceback (most recent call last):
  File "/usr/src/app/include/HydrusServerResources.py", line 258, in ParseFileArguments
    thumbnail_bytes = HydrusFileHandling.GenerateThumbnailBytes( path, target_resolution, mime, duration, num_frames )
  File "/usr/src/app/include/HydrusFileHandling.py", line 101, in GenerateThumbnailBytes
    numpy_image = HydrusImageHandling.ResizeNumPyImage( numpy_image, target_resolution ) # just in case ffmpeg doesn't deliver right
  File "/usr/src/app/include/HydrusImageHandling.py", line 629, in ResizeNumPyImage
    interpolation = cv2.INTER_LANCZOS4
NameError: name 'cv2' is not defined
```

Making the issue here as this seems like it's related to the docker.

The file in question was a 3.6MB video/webm file (1280*720) 25.5 seconds (764 frames)

**Comment by Ryonez** [comment]
Clearing that file, it got hooked up on another webm. Defiantly an issue making thumbnails with that format.

**Comment by Ryonez** [comment]
And now an mp4. Damnit.

**Comment by imtbl** [comment]
Thanks for the report, looks like it fails because cv2 (OpenCV) is not available.

Which actually shouldn‘t happen; according to the hydrus dev, the server should fall back to another library for image handling. See also #1.

As a workaround, using version 350 should be fine as this change only came in with 351. I‘ll correct this for the next release.

**Comment by Ryonez** [comment]
Gotcha, didn't realise cv2 was OpenCV. 

This is a recent setup for me, so I'll just hold the videos back for now.

**Comment by imtbl** [comment]
Just curious, images are fine? Because if that's the case, I'll look at the code and let hydrus dev know that he didn't implement the fallback for videos (which is probably not intended).

Regardless, I hope to release a fixed version (with OpenCV support) either later today or on the weekend.

**Comment by Ryonez** [comment]
The others worked fine, it was just those 2 formats I've noticed issues with so far.

**Comment by imtbl** [comment]
I've made the necessary changes and tested it locally. Everything seems to be working fine. Uploading `video/webm` and `video/mp4` files also didn't produce any errors.

I will make two new releases:

+ `3.0.0`: a new major version due to the switch to the Debian base image; this also includes an updated hydrus server version `351` image on Docker Hub
+ `3.1.0`: the release for hydrus server version `352`

In either case, if you are pulling from Docker Hub, you will just need to (re-)pull the image.

If you are building the image yourself, you will, of course, have to rebuild.

Let me know if you encounter any more issues! :)

---

As expected, the (uncompressed) image size has increased considerably by switching to a Debian base image:

```shell
REPOSITORY                       TAG                 IMAGE ID            CREATED             SIZE
hydrus-server-docker-debian      latest              bcd9e010821d        3 minutes ago       855MB
mserajnik/hydrus-server-docker   latest              d76d073bd3c8        6 days ago          348MB
```

So, as I've stated before, if anyone wants to explore running OpenCV on Alpine to get the image smaller again, I'm open for PRs.
